name: iOS CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      
      - name: Select Xcode 15.0
        run: sudo xcode-select -switch /Applications/Xcode_15.0.app

      - name: Build and Test
        run: |
          xcodebuild test -project BreadDiary.xcodeproj \
            -scheme BreadDiary \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            -enableCodeCoverage YES \
            | xcpretty && exit ${PIPESTATUS[0]}
