name: iOS CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      
      - name: List available Xcode versions
        run: ls -la /Applications/ | grep "Xcode"
      
      - name: Show current Xcode version
        run: xcodebuild -version
        
      - name: Show build settings
        run: xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showBuildSettings
        
      - name: Show available schemes
        run: xcodebuild -project BreadDiary.xcodeproj -list

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project BreadDiary.xcodeproj \
            -scheme BreadDiary \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.1' \
            -enableCodeCoverage YES \
            -verbose \
            | xcpretty && exit ${PIPESTATUS[0]}
