name: iOS CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      
      - name: List Xcode versions
        run: ls -la /Applications/ | grep "Xcode"
      
      - name: Check project structure
        run: |
          echo "Project structure:"
          ls -la
          echo "\nXcode project structure:"
          ls -la BreadDiary.xcodeproj/
          
      - name: Verify project.pbxproj
        run: |
          echo "Project.pbxproj content:"
          cat BreadDiary.xcodeproj/project.pbxproj
          
      - name: Setup Xcode version
        run: |
          echo "Available Xcode versions:"
          ls -la /Applications/Xcode*
          sudo xcode-select -p
          
      - name: Create fresh scheme
        run: |
          mkdir -p BreadDiary.xcodeproj/xcshareddata/xcschemes
          cat > BreadDiary.xcodeproj/xcshareddata/xcschemes/BreadDiary.xcscheme << 'EOL'
          <?xml version="1.0" encoding="UTF-8"?>
          <Scheme LastUpgradeVersion="1500" version="1.7">
             <BuildAction parallelizeBuildables="YES" buildImplicitDependencies="YES">
                <BuildActionEntries>
                   <BuildActionEntry buildForTesting="YES" buildForRunning="YES" buildForProfiling="YES" buildForArchiving="YES" buildForAnalyzing="YES">
                      <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="2DDAF7CA2CFA3F72003859FD" BuildableName="BreadDiary.app" BlueprintName="BreadDiary" ReferencedContainer="container:BreadDiary.xcodeproj"/>
                   </BuildActionEntry>
                </BuildActionEntries>
             </BuildAction>
             <TestAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" shouldUseLaunchSchemeArgsEnv="YES">
                <Testables>
                   <TestableReference skipped="NO">
                      <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="2DDAF7DB2CFA3F74003859FD" BuildableName="BreadDiaryTests.xctest" BlueprintName="BreadDiaryTests" ReferencedContainer="container:BreadDiary.xcodeproj"/>
                   </TestableReference>
                </Testables>
             </TestAction>
             <LaunchAction buildConfiguration="Debug" selectedDebuggerIdentifier="Xcode.DebuggerFoundation.Debugger.LLDB" selectedLauncherIdentifier="Xcode.DebuggerFoundation.Launcher.LLDB" launchStyle="0" useCustomWorkingDirectory="NO" ignoresPersistentStateOnLaunch="NO" debugDocumentVersioning="YES" debugServiceExtension="internal" allowLocationSimulation="YES">
                <BuildableProductRunnable runnableDebuggingMode="0">
                   <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="2DDAF7CA2CFA3F72003859FD" BuildableName="BreadDiary.app" BlueprintName="BreadDiary" ReferencedContainer="container:BreadDiary.xcodeproj"/>
                </BuildableProductRunnable>
             </LaunchAction>
             <ProfileAction buildConfiguration="Release" shouldUseLaunchSchemeArgsEnv="YES" savedToolIdentifier="" useCustomWorkingDirectory="NO" debugDocumentVersioning="YES">
                <BuildableProductRunnable runnableDebuggingMode="0">
                   <BuildableReference BuildableIdentifier="primary" BlueprintIdentifier="2DDAF7CA2CFA3F72003859FD" BuildableName="BreadDiary.app" BlueprintName="BreadDiary" ReferencedContainer="container:BreadDiary.xcodeproj"/>
                </BuildableProductRunnable>
             </ProfileAction>
             <AnalyzeAction buildConfiguration="Debug"/>
             <ArchiveAction buildConfiguration="Release" revealArchiveInOrganizer="YES"/>
          </Scheme>
          EOL

      - name: Show available schemes
        run: xcodebuild -project BreadDiary.xcodeproj -list || true
        
      - name: Clean DerivedData
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          
      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project BreadDiary.xcodeproj \
            -scheme BreadDiary \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.1' \
            -enableCodeCoverage YES \
            -verbose \
            | xcpretty && exit ${PIPESTATUS[0]}
