name: iOS CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Clean DerivedData
      run: |
        echo "Cleaning DerivedData directory..."
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        echo "DerivedData cleaned."
    
    - name: Show Build Settings
      run: |
        xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showBuildSettings || true
        
    - name: Show Available Destinations
      run: |
        xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showdestinations || true
        
    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean test \
          -project BreadDiary.xcodeproj \
          -scheme BreadDiary \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES | xcpretty

    - name: Debug Info
      if: failure()
      run: |
        xcodebuild clean build-for-testing \
          -project BreadDiary.xcodeproj \
          -scheme BreadDiary \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
          -enableCodeCoverage YES \
          -allowProvisioningUpdates \
          | xcpretty
