name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        
    - name: Select Xcode 16.1
      run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
    
    - name: Verify Xcode Selection
      run: xcode-select -p
    
    - name: Install xcode-project-cleaner
      run: sudo gem install xcode-project-cleaner
    
    - name: Clean Xcode Project
      run: xcode-project-cleaner BreadDiary.xcodeproj
    
    - name: List Xcode Project Structure
      run: |
        ls -la
        find . -name "*.xcodeproj" -o -name "*.xcworkspace"
        
    - name: Show Xcode Version
      run: xcodebuild -version
        
    - name: Resolve Dependencies
      run: set -o pipefail && xcodebuild -project BreadDiary.xcodeproj -resolvePackageDependencies
    
    - name: Show Available Schemes
      run: xcodebuild -list
        
    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild test \
          -scheme BreadDiary \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
          -skipPackagePluginValidation \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES | xcpretty
