name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Install Dependencies
      run: |
        xcodebuild -resolvePackageDependencies
        
    - name: Build and Test
      run: |
        xcodebuild clean test \
          -workspace BreadDiary.xcworkspace \
          -scheme BreadDiary \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES
