name: iOS Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Run tests
        run: |
          xcodebuild test -project BreadDiary.xcodeproj -scheme BreadDiaryTests -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.1' -only-testing:BreadDiaryTests

