name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Show Build Settings
      run: xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showBuildSettings
      
    - name: Show Available Destinations
      run: xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showdestinations
      
    - name: Build and Test
      run: |
        xcodebuild clean test \
          -project BreadDiary.xcodeproj \
          -scheme BreadDiary \
          -destination "platform=iOS Simulator,OS=17.0,name=iPhone 14" \
          -testPlan BreadDiaryTests \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
