name: iOS CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
        with:
          clean: true

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app

      - name: Clean DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Resolve Dependencies
        run: xcodebuild -resolvePackageDependencies -project BreadDiary.xcodeproj

      - name: Show Build Settings
        run: xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showBuildSettings

      - name: Show Available Destinations
        run: xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showdestinations

      - name: Debugging: Validate Syntax
        run: plutil -lint BreadDiary.xcodeproj/project.pbxproj

      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild clean test \
            -project BreadDiary.xcodeproj \
            -scheme BreadDiary \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES | xcpretty && exit ${PIPESTATUS[0]}

      - name: Debug Info
        if: failure()
        run: |
          echo "Debugging build issues..."
          xcodebuild clean build-for-testing \
            -project BreadDiary.xcodeproj \
            -scheme BreadDiary \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES | xcpretty
