name: Run Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build and Test
      run: |
        xcodebuild test \
          -scheme BreadDiary \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
          -only-testing:BreadDiaryTests/HomeFeatureTests \
          -only-testing:BreadDiaryTests/SearchFeatureTests \
          -only-testing:BreadDiaryTests/FavoriteFeatureTests
