name: iOS CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-13

    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v3
        with:
          clean: true

      # Seleccionar la versión de Xcode
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      # Limpiar DerivedData (opcional pero recomendado)
      - name: Clean DerivedData
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # Validar project.pbxproj con plutil
      - name: Validate project.pbxproj Syntax
        run: plutil -lint BreadDiary.xcodeproj/project.pbxproj || echo "Syntax errors found in project.pbxproj"

      # Mostrar configuración del proyecto
      - name: Show Build Settings
        run: |
          xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showBuildSettings || true

      # Mostrar destinos disponibles
      - name: Show Available Destinations
        run: |
          xcodebuild -project BreadDiary.xcodeproj -scheme BreadDiary -showdestinations || true

      # Regenerar project.pbxproj si es necesario
      - name: Regenerate project.pbxproj
        if: failure()
        run: |
          echo "Regenerating project.pbxproj due to syntax issues..."
          rm -rf BreadDiary.xcodeproj/project.pbxproj
          xcodebuild -list -project BreadDiary.xcodeproj

      # Compilar y ejecutar pruebas
      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild clean test \
            -project BreadDiary.xcodeproj \
            -scheme BreadDiary \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES | xcpretty && exit ${PIPESTATUS[0]}

      # Depurar si falla
      - name: Debug Info
        if: failure()
        run: |
          echo "Debugging build issues..."
          xcodebuild clean build-for-testing \
            -project BreadDiary.xcodeproj \
            -scheme BreadDiary \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES | xcpretty
