name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
        
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
        
    - name: List Xcode Project Structure
      run: |
        ls -la
        find . -name "*.xcodeproj" -o -name "*.xcworkspace"
        
    - name: Show Xcode Version
      run: xcodebuild -version
        
    - name: Show Available Schemes
      run: xcodebuild -list
        
    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild test \
          -scheme BreadDiary \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
          -skipPackagePluginValidation \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES | xcpretty
